name: WhatsApp Bot

on:
  workflow_dispatch:          # Manual trigger
  push:
    branches: ["main"]
  schedule:
    - cron: "0 */6 * * *"     # Restar every 6 hours

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node index.js
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
          # Add any other bot environment variables here
